Feature/cloud 912 okta app
variant-inc/terraform-okta-oauth-app pull request #1
Opened 2021-12-07 14:23 UTC by salyateem13

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes [#8](https://usxtech.atlassian.net/browse/CLOUD-8)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Sanity Testing

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added documentation to test

2021-12-07 14:34 UTC, vibindaniel requested changes
There is no `okta_app_group_assignment` found. Can you add all options from the resource and make some as defaults?

2021-12-07 14:34 UTC, vibindaniel commented on provider.tf
> +provider "okta" {
Can the requirements be a single object?

2021-12-07 14:34 UTC, vibindaniel commented on versions.tf
> +            version = "~> 3.20"
Change version to `>= 3.20`

2021-12-07 14:34 UTC, vibindaniel commented on main.tf
> +
remove empty line

2021-12-07 14:34 UTC, vibindaniel commented on main.tf
> +    label = "${var.name}-${var.environment}"
"${var.environment}-${var.name}"

2021-12-07 14:51 UTC, salyateem13 commented on main.tf
> +    label = "${var.name}-${var.environment}"
Was thinking ${var.name}-${var.environment} would be better in UI... see app list sorted by app name rather than by env

2021-12-09 15:18 UTC, rchengvariant approved these changes

2021-12-09 18:52 UTC, rchengvariant approved these changes

2021-12-09 19:53 UTC, LeeHughsVariant approved these changes

2021-12-09 20:46 UTC, merged